blank_issues_enabled: false
contact_links:
  - name: Open New Issue
    url: https://github.com/Bvisi0n/gamemathlib/issues/new?template=new-issue.yml
    about: Use this to open a new issue for the library.
